### ISSUE TITLE
Convert annotation does not work at Key-value-mapping

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#146]
The @Convert annotation does not seem to work at all (I use it together with an AttributeConverter)- however, it always fails at Caused by: 
```
java.util.NoSuchElementException at java.util.Collections$EmptyIterator.next(Collections.java:4189) at 
org.jnosql.artemis.DefaultConverters.getInstance(DefaultConverters.java:41) at org.jnosql.artemis.DefaultConverters.get(DefaultConverters.java:37) at org.jnosql.artemis.DefaultConverters$Proxy$_$$_WeldClientProxy.get(Unknown Source) at java.util.Optional.map(Optional.java:215)
```

**Comment by adam-waldenberg** [comment]
Fixed! :)

**Comment by otaviojava** [comment]
Thank you, I'll close this issue
