### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by anhhoang87** [eclipse/jnosql#560]
### Which JNoSQL project the issue refers to?

JNoSQL Databases

### Bug description

I keep running into an error where there is an exception to connect to the redis database using org.eclipse.jnosql.databases:jnosql-redis:1.1.1. After getting this error, I have to restart the whole service. Is there a way to catch the exception, close the connection, and open a new one?

http-nio-8080-exec-4] Error happened when creating json token Attempting to read from a broken connection
redis.clients.jedis.exceptions.JedisConnectionException: Attempting to read from a broken connection
at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:346)
at redis.clients.jedis.Connection.getOne(Connection.java:332)
at redis.clients.jedis.Connection.executeCommand(Connection.java:137)
at redis.clients.jedis.Jedis.set(Jedis.java:4893)
at org.eclipse.jnosql.databases.redis.communication.RedisBucketManager.put(RedisBucketManager.java:59)
at org.eclipse.jnosql.databases.redis.communication.RedisBucketManager.put(RedisBucketManager.java:64)
at org.eclipse.jnosql.communication.keyvalue.BucketManager$$OwbNormalScopeProxy0.put(org/eclipse/jnosql/communication/keyvalue/BucketManager.java)
at org.eclipse.jnosql.mapping.keyvalue.AbstractKeyValueTemplate.lambda$put$0(AbstractKeyValueTemplate.java:49)
at org.eclipse.jnosql.mapping.keyvalue.AbstractKeyValueTemplate.lambda$toUnary$8(AbstractKeyValueTemplate.java:160)

### JNoSQL Version

JNoSQL version 1.1.1

### Steps To Reproduce

Not sure how to reproduce the issue but I'm building a web service using jakarta ee with redis integration. The service is running on tomee and the redis connection configuration is set up using micro profile

**Comment by otaviojava** [comment]
@anhhoang87 we will work on it.

**Comment by otaviojava** [comment]
I've released version 1.1.3 with this change; please let me know if it fixed your issue.

Thanks.
